servers:
  - name: Ubuntu VM Server
    hostname: 192.168.2.226
    username: root
    password: root
    port: 22

tasks:
   vsftpd:
     vsftp_install: "true"
     vsftp_configure: "true"
   vsftpd_user:
     - username: ftpuser2
        password: password2
     - username: ftpuser3
       password: password2
  vsftpd_config:
     config_file: /etc/vsftpd.conf
     settings:
       listen: YES
       listen_ipv6: NO
       anonymous_enable: NO
       local_enable: YES
       write_enable: YES
       local_umask: 022
       dirmessage_enable: YES
       use_localtime: YES
       chroot_local_user: YES
       chroot_list_enable: YES
       chroot_list_file: /etc/vsftpd/chroot_list
  service:
     - name: Restart vsftpd
       service_name: vsftpd
       action: restart